version: "3"

services:
        mysql_db:
                container_name: mysql_container
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root1234
                        MYSQL_DATABASE: wordpress_db
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                volumes:
                        - mysql:/var/lib/mysql
#Wordpress

        wordpress:
                depends_on:
                        - mysql_db
                container_name: wordpress_app
                image: wordpress:latest
                restart: always
                ports:
                        - "8000:80"
                environment:
                        WORDPRESS_DB_HOST: mysql_db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_NAME: wordpress_db
                volumes: ["./:/var/www/html"]

volumes:
        mysql: {}
